sudo: required

services:
  - docker

language: generic

branches:
  only:
    - master

jobs:
  include:
    - state: build
      script: bash ./chrome build --push
      on:
        branch: master

